@startuml
title Other Tag Pollution Attack Model

start

#gold://is_success// = false;

while (more compromised nodes?) is (yes)
    :move to the compromised node on the path to the sink;
    :choose a compromised key from //key_pool// randomly\n(equivalent to tampering with a corresponding MAC);
    #greenyellow://path_success// = true;
    while (reach the sink?) is (no)
        :move to the next node;
        if (compromised?) then (yes)
            :pass;
        else (no)
            if (compromised key in\nthe key subset of the node?) then (yes)
                :detected;
                #greenyellow://path_success// = false;
                break
            else (no)
                :not detected;
            endif
        endif

    endwhile (yes)

    if (//path_success// ?) then (yes)
        #gold://is_success// = true;
        break
    else (no)
        :try another compromised node;
    endif

endwhile (no)

if (//is_success// ?) then (yes)
    :tag pollution attack success;
else (no)
    :tag pollution attack fail;
endif

stop
@enduml